
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import org.json.simple.parser.ParseException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yuan
 */
public class findStudent extends javax.swing.JFrame {

    /**
     * Creates new form findStudent
     */
    
    private String name;
    public findStudent() {
        initComponents();
        setSize(880,540);
        
        Action okBtAction = new AbstractAction("Ok") {
        @Override
        public void actionPerformed(ActionEvent e) {
            enter();
        }
        };
     
     
     String key1 = "Ok";
             
     okBt.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0), key1);
     okBt.getActionMap().put(key1, okBtAction);
     
    }

    
    private void enter(){
        this.name=targetStudent.getText();
        DashBoard temp;
        try {
            temp = new DashBoard(this.name);
            temp.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(findStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(findStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        findUserReturn = new javax.swing.JButton();
        targetStudent = new javax.swing.JTextField();
        okBt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Which user are you checking? ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 320, 30));

        findUserReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8-back-24.png"))); // NOI18N
        findUserReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findUserReturnActionPerformed(evt);
            }
        });
        getContentPane().add(findUserReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 50, 50));

        targetStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetStudentActionPerformed(evt);
            }
        });
        getContentPane().add(targetStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 221, -1));

        okBt.setFont(new java.awt.Font("Impact", 0, 13)); // NOI18N
        okBt.setText("OK");
        okBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtActionPerformed(evt);
            }
        });
        getContentPane().add(okBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bank Gothic", 1, 13)); // NOI18N
        jLabel3.setText("Press 'return' to go to Main Menu, or 'space' to click 'Ok'");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/game_background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 940, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtActionPerformed
    enter();       // TODO add your handling code here:
       
        
    }//GEN-LAST:event_okBtActionPerformed

    private void findUserReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findUserReturnActionPerformed
        dispose();
        User currUser = new User("Instructor");
        currUser.setInstructor(true);
        new menu(currUser).setVisible(true);// TODO add your handling code here:
        
    }//GEN-LAST:event_findUserReturnActionPerformed

    private void targetStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton findUserReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okBt;
    private javax.swing.JTextField targetStudent;
    // End of variables declaration//GEN-END:variables
}
