
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author siddh device
 */
public class gameOver extends javax.swing.JFrame {

    /**
     * Creates new form gameOver
     */
    private User currUser;
    private String clickSound;

    public gameOver(User currUser) {
        this.currUser = currUser;

        initComponents();
        setSize(880, 540);

        clickSound = ("src/user/Womp Womp Womp sound effect.wav"); // Load default music
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameOverText = new javax.swing.JLabel();
        playAgainButton = new javax.swing.JButton();
        goToMainMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(20, 20));
        getContentPane().setLayout(null);

        gameOverText.setBackground(new java.awt.Color(0, 0, 204));
        gameOverText.setFont(new java.awt.Font("Krungthep", 1, 70)); // NOI18N
        gameOverText.setForeground(new java.awt.Color(255, 255, 255));
        gameOverText.setText("GAME OVER !");
        getContentPane().add(gameOverText);
        gameOverText.setBounds(230, 170, 490, 110);

        playAgainButton.setFont(new java.awt.Font("Impact", 0, 13)); // NOI18N
        playAgainButton.setText("Play Again?");
        playAgainButton.setBackground(Color.GRAY);
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playAgainButton);
        playAgainButton.setBounds(280, 360, 120, 50);

        goToMainMenu.setFont(new java.awt.Font("Impact", 0, 13)); // NOI18N
        goToMainMenu.setText("Main Menu");
        goToMainMenu.setBackground(Color.GRAY);
        goToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToMainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(goToMainMenu);
        goToMainMenu.setBounds(490, 360, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/Word.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        try {
            playGame tryAgain = new playGame(currUser, currUser.getLevel());
            tryAgain.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(gameOver.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_playAgainButtonActionPerformed

    private void goToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToMainMenuActionPerformed
        new menu(currUser).setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_goToMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameOverText;
    private javax.swing.JButton goToMainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton playAgainButton;
    // End of variables declaration//GEN-END:variables
}
