/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author shainatodi
 */
//import java.util.Scanner;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setSize(880, 540); 
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        attemptLogin = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Login");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 36));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 36));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 36));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 20, 81, 64);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Password: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 220, 110, 20);

        password.setText("jPasswordField1");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(530, 270, 230, 23);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(503, 115, 287, 0);

        attemptLogin.setFont(new java.awt.Font("Impact", 0, 13)); // NOI18N
        attemptLogin.setText("Login");
        attemptLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptLoginActionPerformed(evt);
            }
        });
        attemptLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                attemptLoginKeyPressed(evt);
            }
        });
        getContentPane().add(attemptLogin);
        attemptLogin.setBounds(530, 330, 78, 23);

        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8-back-24.png"))); // NOI18N
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(back_button);
        back_button.setBounds(800, 30, 45, 55);

        jButton1.setFont(new java.awt.Font("Impact", 0, 13)); // NOI18N
        jButton1.setText("Show Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(628, 330, 130, 23);

        jLabel5.setFont(new java.awt.Font("Bank Gothic", 1, 13)); // NOI18N
        jLabel5.setText("click on password box & Press 'return' to hide a visible password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 470, 510, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/game_background.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 910, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attemptLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptLoginActionPerformed
      //  char[] passValue = password.getPassword();  
        String passValue = String.valueOf(password.getPassword());//get user entered pasword from the textField2  
        password.setEchoChar('*');
    if (passValue.equals("INgroup45")) {
           // Entering Instructor Mode
           this.dispose();
            new findStudent().setVisible(true);

        } else if (passValue.equals("DEgroup45")) {
            //Entering Developer Mode
            this.dispose();
            new debugMode().setVisible(true);

            
        } else {
            //return "Incorrect password entered";
    JOptionPane.showMessageDialog(null, "Incorrect password entered");
              //  System.out.println("Incorrect password entered");

        }// TODO add your handling code here:
          
    }//GEN-LAST:event_attemptLoginActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
            this.dispose();

           // new ProfilesFrame().setVisible(true);
    }//GEN-LAST:event_back_buttonActionPerformed

    private void attemptLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attemptLoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_attemptLoginKeyPressed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
       String passValue = String.valueOf(password.getPassword());  
       password.setEchoChar('*');//get user entered pasword from the textField2  
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String passValue = String.valueOf(password.getPassword());  
 password.setEchoChar((char)0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attemptLogin;
    private javax.swing.JButton back_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
