
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.parser.ParseException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yuan
 */
public class sbFrame extends javax.swing.JFrame {

    /**
     * Creates new form inputName
     */
    private User currUser;
    public sbFrame(User newUser) throws ParseException, IOException {
        currUser = newUser;
        initComponents();
        setSize(880,540);
        setResizable(false);

        setBoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rk1 = new javax.swing.JTextField();
        rk2 = new javax.swing.JTextField();
        rk3 = new javax.swing.JTextField();
        rk4 = new javax.swing.JTextField();
        rk5 = new javax.swing.JTextField();
        rk6 = new javax.swing.JTextField();
        rk7 = new javax.swing.JTextField();
        rk8 = new javax.swing.JTextField();
        rk9 = new javax.swing.JTextField();
        rk10 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        sbReturnBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scoreboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("|Scoreboard|");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 200, -1));

        rk1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rk1.setText("jTextField1");

        rk2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rk2.setText("jTextField1");

        rk3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rk3.setText("jTextField1");

        rk4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rk4.setText("jTextField1");
        rk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rk4ActionPerformed(evt);
            }
        });

        rk5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rk5.setText("jTextField1");

        rk6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rk6.setText("jTextField1");

        rk7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rk7.setText("jTextField1");

        rk8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rk8.setText("jTextField1");

        rk9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rk9.setText("jTextField1");

        rk10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rk10.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rk1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
            .addComponent(rk2)
            .addComponent(rk3)
            .addComponent(rk4)
            .addComponent(rk5)
            .addComponent(rk6)
            .addComponent(rk7)
            .addComponent(rk8)
            .addComponent(rk9)
            .addComponent(rk10)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rk1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rk2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rk3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rk4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rk5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rk6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rk7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rk8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rk9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rk10, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 410));

        jList2.setFont(new java.awt.Font("Krungthep", 0, 28)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setAutoscrolls(false);
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 420));

        sbReturnBt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        sbReturnBt.setForeground(new java.awt.Color(242, 242, 242));
        sbReturnBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8-back-24.png"))); // NOI18N
        sbReturnBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbReturnBtActionPerformed(evt);
            }
        });
        getContentPane().add(sbReturnBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 50, 50));

        jLabel2.setFont(new java.awt.Font("Bank Gothic", 1, 13)); // NOI18N
        jLabel2.setText("Press 'return' to go back to main menu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/game_background.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbReturnBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbReturnBtActionPerformed
        new menu(currUser).setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_sbReturnBtActionPerformed

    private void rk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rk4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rk4ActionPerformed

    /**
     * @param args the command line arguments
     */

    public void setBoard() throws ParseException, IOException{
        //System.out.println("here????");

        scoreBoard sb=new scoreBoard();
        rk1.setText(sb.getUserByRk(0).getName()+"----------------------------------"+(sb.getUserByRk(0).getTotalScore()));
        rk2.setText(sb.getUserByRk(1).getName()+"----------------------------------"+(sb.getUserByRk(1).getTotalScore()));
        rk3.setText(sb.getUserByRk(2).getName()+"----------------------------------"+(sb.getUserByRk(2).getTotalScore()));
        rk4.setText(sb.getUserByRk(3).getName()+"----------------------------------"+(sb.getUserByRk(3).getTotalScore()));
        rk5.setText(sb.getUserByRk(4).getName()+"----------------------------------"+(sb.getUserByRk(4).getTotalScore()));
        rk6.setText(sb.getUserByRk(5).getName()+"----------------------------------"+(sb.getUserByRk(5).getTotalScore()));
        rk7.setText(sb.getUserByRk(6).getName()+"----------------------------------"+(sb.getUserByRk(6).getTotalScore()));
        rk8.setText(sb.getUserByRk(7).getName()+"----------------------------------"+(sb.getUserByRk(7).getTotalScore()));
        rk9.setText(sb.getUserByRk(8).getName()+"----------------------------------"+(sb.getUserByRk(8).getTotalScore()));
        rk10.setText(sb.getUserByRk(9).getName()+"---------------------------------"+(sb.getUserByRk(9).getTotalScore()));

        
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField rk1;
    private javax.swing.JTextField rk10;
    private javax.swing.JTextField rk2;
    private javax.swing.JTextField rk3;
    private javax.swing.JTextField rk4;
    private javax.swing.JTextField rk5;
    private javax.swing.JTextField rk6;
    private javax.swing.JTextField rk7;
    private javax.swing.JTextField rk8;
    private javax.swing.JTextField rk9;
    private javax.swing.JButton sbReturnBt;
    // End of variables declaration//GEN-END:variables
}
