import javax.swing.JOptionPane;

public class SettingsFrame extends javax.swing.JFrame {
    private String[] musicTracks;
    private int currentTrackIndex;
    private int volume;
    private boolean soundEffectsEnabled;
    private MusicPlayer musicPlayer; // Import the MusicPlayer class and create an instance


    /**
     * Creates new form SettingsFrame
     */
    private User currUser;
    
    
    public SettingsFrame(User newUser) {
        currUser = newUser;
        initComponents();
        setSize(880, 540);
        initializeSettings();
        musicPlayer = new MusicPlayer(); // Instantiate a MusicPlayer object
        musicPlayer.stopMusic();
        musicPlayer.loadMusic("/music/Defusing the Bomb.wav"); // Load default music
        updateGUI();
    }
//Method to initialize default settings
    private void initializeSettings() {
        // Initialize default settings
    musicTracks = new String[] { "Defusing the Bomb", "Intense Background Music", "Mission Impossible - Main Theme" };
    volume = 50; // Default volume
    soundEffectsEnabled = true; // Sound effects enabled by default
    currentTrackIndex = 0; // Start with the first music track
   
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSlider2 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Audio");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 240, 82, 23);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Volume");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 310, 82, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Audio 1", "Audio 2", "Audio 3", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(450, 240, 157, 23);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Settings");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 100, 90, 23);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8-back-24.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(830, 10, 40, 50);

        jSlider2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSlider2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        getContentPane().add(jSlider2);
        jSlider2.setBounds(440, 310, 200, 20);

        jLabel5.setFont(new java.awt.Font("Bank Gothic", 1, 13)); // NOI18N
        jLabel5.setText("Press 'return' to go back to main menu");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 500, 279, 15);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/game_background.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 880, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    setCurrentTrackIndex(jComboBox1.getSelectedIndex());
    
    // Stop the currently playing music before loading the new one
    musicPlayer.stopMusic();
    
    String[] fileNames = { "Defusing the Bomb.wav", "intense background music.wav", "Mission Impossible - Main Theme.wav" };
    String selectedMusic = "/music/" + fileNames[currentTrackIndex];
    musicPlayer.loadMusic(selectedMusic); // Load selected music
    musicPlayer.playMusic(); // Start playing the newly selected music
              
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Handle button click to return to the main menu
        this.dispose(); // Dispose of the settings frame
        // Show the main menu frame
        menu menuPage = new menu(this.currUser);
        menuPage.setVisible(true);
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSlider2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSlider2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider2AncestorAdded

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        volume = jSlider2.getValue();
    if (musicPlayer != null) {
        musicPlayer.setVolume(volume / 100.0f); // Update the volume of the music player
    }
    }//GEN-LAST:event_jSlider2StateChanged

    

//Method to update GUI components with current settings
    private void updateGUI() {
        jSlider2.setValue(volume);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(musicTracks));
        jComboBox1.setSelectedIndex(currentTrackIndex);
    }


    private void setCurrentTrackIndex(int index) {
         // Set the current music track index
        if (index >= 0 && index < musicTracks.length) {
            currentTrackIndex = index;
            System.out.println("Selected music track: " + musicTracks[index]);
        } else {
            System.err.println("Invalid track index.");
        }
    }
    
    private void toggleSoundEffects() {
    // Toggle sound effects
        soundEffectsEnabled = !soundEffectsEnabled;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSlider jSlider2;
    // End of variables declaration//GEN-END:variables
}
