
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author siddh device
 */
public class summaryPage extends javax.swing.JFrame {

    /**
     * Creates new form summaryPage
     */
    
    private User currUser;
    private int level;
    
    public summaryPage(User newUser, int level) throws IOException {
        this.currUser = newUser;
        this.level = level;
        initComponents();
        currUser.setLevel(currUser.getLevel()+1);
        completionText1.setVisible(false);
        completionText2.setVisible(false);
        setSize(880, 540);
        setLevel();
        setScore();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        currScore = new javax.swing.JLabel();
        currLevel = new javax.swing.JLabel();
        playAgainButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        completionText1 = new javax.swing.JLabel();
        completionText2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        currScore.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        currScore.setText("Score:");
        getContentPane().add(currScore);
        currScore.setBounds(370, 300, 120, 20);

        currLevel.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        currLevel.setText("Level: X");
        getContentPane().add(currLevel);
        currLevel.setBounds(380, 240, 100, 30);

        playAgainButton.setFont(new java.awt.Font("Impact", 0, 13)); // NOI18N
        playAgainButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8-next-22.png"))); // NOI18N
        playAgainButton.setText("Next Level");
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playAgainButton);
        playAgainButton.setBounds(130, 440, 130, 40);

        jButton1.setFont(new java.awt.Font("Impact", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8-menu-22.png"))); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 440, 130, 40);

        completionText1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        completionText1.setForeground(new java.awt.Color(0, 102, 102));
        completionText1.setBackground(Color.black);
        completionText1.setOpaque(true);
        completionText1.setText("Congratulations! You have completed the game!");
        getContentPane().add(completionText1);
        completionText1.setBounds(70, 60, 760, 70);

        completionText2.setBackground(Color.BLACK);
        completionText2.setBackground(Color.black);
        completionText2.setOpaque(true);
        completionText2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        completionText2.setForeground(new java.awt.Color(0, 102, 102));
        completionText2.setText("You can try out our challenge level by clicking \"Next Level\"");
        getContentPane().add(completionText2);
        completionText2.setBounds(220, 150, 440, 23);

        saveButton.setFont(new java.awt.Font("Impact", 0, 13)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8-save-22.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(370, 440, 130, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 220, 180, 130);
        jLabel2.setBackground(Color.LIGHT_GRAY);
        jLabel2.setOpaque(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/game_background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        try {
            playGame nextLevel = new playGame(this.currUser, currUser.getLevel());
            nextLevel.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(summaryPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_playAgainButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new menu(currUser).setVisible(true);
        dispose(); 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            currUser.saveUser();
        } catch (IOException ex) {
            Logger.getLogger(summaryPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    private void setLevel(){
        int realLevel = level;
        if(realLevel == 4){
            completionText1.setVisible(true);
            completionText2.setVisible(true);
        }
        currLevel.setText("Level " + realLevel);
    }
    private void setScore(){
        int displayScore = currUser.getLevel();
        if(currUser.getLevel() > 5){
            displayScore = 5;
        }
        displayScore = currUser.getLevelScore(displayScore-1);
        currScore.setText("Score " + displayScore);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel completionText1;
    private javax.swing.JLabel completionText2;
    private javax.swing.JLabel currLevel;
    private javax.swing.JLabel currScore;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
